// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-help'
  | 'pref-html-blocklist'
  | 'pref-html-blocklist-help'
  | 'pref-title'
  | 'pref-translate-api-base'
  | 'pref-translate-api-key'
  | 'pref-translate-help'
  | 'pref-translate-model'
  | 'pref-translate-prompt-add'
  | 'pref-translate-prompt-content'
  | 'pref-translate-prompt-name'
  | 'pref-translate-prompt-preview'
  | 'pref-translate-prompt-select'
  | 'pref-translate-rpm'
  | 'pref-translate-title'
  | 'prefs-title';
