// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-help'
  | 'pref-html-blocklist'
  | 'pref-html-blocklist-help'
  | 'pref-inline-css'
  | 'pref-inline-css-help'
  | 'pref-title'
  | 'pref-translate-api-base'
  | 'pref-translate-api-key'
  | 'pref-translate-help'
  | 'pref-translate-model'
  | 'pref-translate-parallel-enabled'
  | 'pref-translate-parallel-reassign'
  | 'pref-translate-parallel-providers'
  | 'pref-translate-prompt-add'
  | 'pref-translate-prompt-content'
  | 'pref-translate-prompt-name'
  | 'pref-translate-prompt-preview'
  | 'pref-translate-prompt-select'
  | 'pref-translate-provider-delete'
  | 'pref-translate-provider-name'
  | 'pref-translate-provider-new'
  | 'pref-translate-provider-save'
  | 'pref-translate-provider-select'
  | 'pref-translate-rpm'
  | 'pref-translate-temperature'
  | 'pref-translate-title'
  | 'prefs-title';
