// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "htmlBlocklist": string;
      "translationApiBaseUrl": string;
      "translationApiKey": string;
      "translationModel": string;
      "translationRPM": number;
      "translationPrompts": string;
      "translationPromptSelection": string;
    };
  }
}
